### ISSUE TITLE
Sideloading documentation doesn't explain how to deal with caching in Word 2016 (Windows 10)

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-js-docs#1011]
Updating/refreshing previously loaded add-ins is fairly straightforward on OSX and web (windows and mac)

However, side-loading into Word 2016 on Windows 10 incurs some seriously sticky caching and there seems to be no easy way to force Word 2016 to "refresh" a previously loaded add-in without bumping the version number in the manifest.

Is there a way to delete a cache of a previously loaded add-in in Word 2016 on Windows? If so what is it, and could we have it in the documentation?

**Comment by fergiemcdowall** [comment]
Pages like this: https://dev.office.com/docs/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

**Comment by kbrandl** [comment]
@fergiemcdowall -- thank you for the documentation request and apologies for the delayed response. Regarding the question you've asked -- please see the answer on this Stack Overflow post:  https://stackoverflow.com/questions/44309909/invalidate-ms-word-cache-for-testing-add-ins, which appears to provide the information that you're seeking.  (I've also labeled this GitHub issue as a documentation request, so that it's on the radar for future consideration.)

**Comment by kbrandl** [comment]
In addition to the SO post that I linked to in my previous comment, the docs have also been updated with this info: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#clear-the-office-cache.  (Closing this issue since it's been resolved.)
