### ISSUE TITLE
Excel Desktop Add-In Does Not Load HTTP 4xx HTML response

### ISSUE THREAD

**Issue by jwesly** [OfficeDev/office-js-docs#1053]
I've been testing around on Excel Desktop for Mac and it looks like when Excel sees these error codes, it assumes the add-in is unreachable even if there is an HTML response. This is problematic because I have to interface with a login service that returns a 400 status on incorrect login. What's the rationale on refusing to load the add-in vs just showing the server response in the taskpane? 

(Office.initialize has already been called in this case, after which I redirected to the page with 400 status)

**Comment by mlafleur** [comment]
I would suggest posting this on [Stack Overflow with the tag `office-js`.](https://stackoverflow.com/questions/tagged/office-js) rather than here. This repository is focused only on documentation set, not the library itself. This forum is where you would file documentation errors/omissions while Stack Overflow is for issues you run into with the library itself.
