### ISSUE TITLE
Visio API - Not able to deselect all shapes

### ISSUE THREAD

**Issue by advdberg** [OfficeDev/office-js-docs#1084]
Article: https://github.com/OfficeDev/office-js-docs/tree/cb166f02ff90bae93b9740436295c7c300376dec/reference/visio 

Issue: There is no option to deselect all shapes, when setting the select = false on one shape, it automatically selects the following shape

We're building a SharePoint app with an integrated Visio Online viewer and we're communicating with the Visio Online API for several interactions with the diagram. But we're not able to deselect all shapes when one shape is selected. It's manually possible to click outside of the Visio page but it's not possible by code. Deselecting a shape individually wil automatically select the following shape so that's also no solution.

**Comment by rahul-mi** [comment]
Hi advdberg

Visio Online supports selecting only one shape at a time. So when one shape is selected, automatically all other shapes get de-selected.

There is a gap in the APIs that you can't de-select a shape programmatically, so that all shapes are in a de-selected state. We have noted the issue and will try to improve it in future.

Meanwhile, we would like to understand more about your scenario. Would [ShapeView.Highlight ](https://dev.office.com/reference/add-ins/visio/shapeview) help your cause? You can use the below code to highlight or hide it.

var view = shape.view; 
view.highlight = {color:"#0000FF", width:2}; 
//for no highlight
view.highlight = null;  

Regards
Rahul Mittal | Program Manager | Microsoft Visio

**Comment by advdberg** [comment]
Hi Rahul,

Thanks for your reply.

We've developed a Provider hosted SharePoint Add-in, where we combine showing a Visio file and showing tasks from a SharePoint list to provide users a guided way of following a Business Process and taking care of remaining (and already closed) tasks.

We can navigate through the add-in by clicking on shapes inside the Visio or on tasks shown outside the Visio. When navigating outside the Visio to another page/task, we also update the Visio through the API with the selection. In some cases we should end up deselecting all shapes, and that's the point we did found out that it's currently not supported through API.

We already did found out about the Highlight option, but as we are also using the Visio select for navigating inside our application, the Visio itself selects a shape when clicked on it. So we then should have the option to deselect it, and highlighting or 'de-highlighting' will not be sufficiënt.

Is there a place where we can follow requests/issues/improvements? We would like to have our customers informed about future improvements/fixes as soon as possible.

Regards,

Ad van den Berg

**Comment by rahul-mi** [comment]
Please use https://visio.uservoice.com/forums/368199-visio-online for posting suggestions and tracking imrovements.

Regards
Rahul

**Comment by advdberg** [comment]
Thanks, posted it right away: https://visio.uservoice.com/forums/368199-visio-online/suggestions/31490842-make-it-possible-to-de-select-one-or-all-shapes-fr

**Comment by rahul-mi** [comment]
The issue of de-selecting the shape is fixed now. You can use shape.select=false; for de-selecting a shape.
