### ISSUE TITLE
Failed to load word add-in

### ISSUE THREAD

**Issue by gomteshhatgine** [OfficeDev/office-js-docs#1135]
Hi,
I have created word add-in which while loading that add-in I am first authenticate that user by giving 
`window.open(signInUrl + "?redirectUrl=" + redirectUrl, 'AuthPopup', 'width=500,height=500,centerscreen=1,menubar=0,toolbar=0,location=0,personalbar=0,status=0,titlebar=0,dialog=1');
`

Iframe window to login then user is login into then word add-in gets loaded.
In such scenario that iframe window is opening in IE even OS having different default browser like chrome,firefox.

But suddenly for authenticating window is opening in OS default browser such as chrome , Firefox etc instead of Iframe and **after login user not redirecting to word add-in** 
Even I have not done any change in code
Also as mentioned in code it should open in iframe even its opening before but suddenly uses default browser

**Comment by mlafleur** [comment]
Could you please post this question in [Stack Overflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and tag your question with `microsoft-graph`? This repository a good forum for receiving technical support on the API itself. 

This forum is specifically for errors/issues with the Microsoft Graph Documentation set rather than the API itself. While there is certainly overlap, questions regarding the use of Microsoft should be posted on Stack Overflow where you'll likely get a quicker response and benefit other developers facing the same challenges.
