### ISSUE TITLE
For Range.getgetResizedRange object Error: TypeError: Cannot read property 'isSetSupported' of undefined

### ISSUE THREAD

**Issue by sajidsheik** [OfficeDev/office-js-docs#1168]
Thank you for helping us to improve the Office Add-ins documentation.

So that we can better assist you, please note the following:
- If you have a question, need help, or are experiencing an issue with your code, we encourage you to post your question or issue on **Stack Overflow**. Tag your question with [office-js](http://stackoverflow.com/questions/tagged/office-js)
- If you have a feature suggestion, please post your idea on our [**User Voice**](https://officespdev.uservoice.com/) page, and vote for your suggestions there.
- If you have an issue with the documentation, please provide the information here, or feel free to submit a pull request with your suggested changes. We will review your contributions and update our documentation accordingly.

Please remove this text before posting your documentation issue. thank you

------------
 
Article:

Issue:

**Comment by sajidsheik** [comment]
For Excel Addin

**Comment by mlafleur** [comment]
Could you please post this question in [Stack Overflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and tag your question with `microsoft-graph`? This repository a good forum for receiving technical support on the API itself. 

This forum is specifically for errors/issues with the Microsoft Graph Documentation set rather than the API itself. While there is certainly overlap, questions regarding the use of Microsoft should be posted on Stack Overflow where you'll likely get a quicker response and benefit other developers facing the same challenges. 

Be sure an include a complete description of your problem and the code you're using to make the call. Without enough detail the community won't be able to provide any guidance.

**Comment by lindalu-MSFT** [comment]
p.s. @mlafleur Thank you for this fantastic boilerplate response! I'll try to keep up with these open issues and reply and close as well.
