### ISSUE TITLE
CallOuts and MouseEvents

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-js-docs#1187]
**Improvement to the CallOut doc: https://developer.microsoft.com/en-us/fabric#/components/callout (and I think this could also apply to ContextualMenu)**

A pretty typical user scenario is "right click anywhere on the page" -> "get up some info" (a menu, or an explanation box). In Fabric, you would do this by positioning a `CallOut` or `ContextualMenu` around a mouse click.

"Open a CallOut from a mouse click" is only partially, tantalisingly documented (In `office-ui-fabric-react@4.x` you can sniff out the coords of a click and then initialise a CallOut by setting `targetPoint`. However this method is marked as _depreciated_, and doesn't seem to work at all in `office-ui-fabric-react@5.x`).

The docs say that a CallOut can be positioned by passing a MouseEvent object to it, but no examples are provided.

IMPROVEMENTS TO DOCS:

1. As a developer I would like to see an example in the [Variants section](https://developer.microsoft.com/en-us/fabric#Variants) of positioning a CallOut by setting `target` with a `MouseEvent`
2. If `targetPoint` is in fact not available in `office-ui-fabric-react@5.x`, then the docs should be updated to reflect this

**Comment by kbrandl** [comment]
@LezaMax -- can you please route this issue to the appropriate contact on the UI Fabric team?

**Comment by Jahnp** [comment]
Hey @fergiemcdowall, Peter from the Fabric team here. This actually looks like a great area of improvement for [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) rather than office.js. Would you mind [opening this issue there](https://github.com/OfficeDev/office-ui-fabric-react/issues)? We've actually been planning to add an example of this behavior for some time, and it'd be great to have a request to associate it with. Thanks!
