### ISSUE TITLE
Office 365 Excel Loading ten thousand all records throttle ,how handle the range assign for large data

### ISSUE THREAD

**Issue by sajidsheik** [OfficeDev/office-js-docs#1200]
Thank you for helping us to improve the Office Add-ins documentation.

So that we can better assist you, please note the following:
- If you have a question, need help, or are experiencing an issue with your code, we encourage you to post your question or issue on **Stack Overflow**. Tag your question with [office-js](http://stackoverflow.com/questions/tagged/office-js)
- If you have a feature suggestion, please post your idea on our [**User Voice**](https://officespdev.uservoice.com/) page, and vote for your suggestions there.
- If you have an issue with the documentation, please provide the information here, or feel free to submit a pull request with your suggested changes. We will review your contributions and update our documentation accordingly.

Please remove this text before posting your documentation issue. thank you

------------
 
Article:

Issue:

**Comment by sajidsheik** [comment]
VM251:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.1.1&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1510605706908&time-delta-to-apply-millis=4213 503 (All records were throttled.)



All records were throttled 
and no records are displaying,promises is both resolved and reject in this cases

**Comment by lindalu-MSFT** [comment]
Hi @sajidsheik,

Could you please post this question in [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and tag your question with office-js? This problem has to do with code and not a documentation error. 

This forum is specifically for errors/issues with the documentation set rather than the API itself. While there is certainly overlap, questions regarding the use of the library should be posted on Stack Overflow where you'll likely get a quicker response and benefit other developers facing the same challenges.

If you have a question about the documentation, please let me know. Thanks, Linda
