### ISSUE TITLE
Chart Object for Word?

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1210]
I want to create a chart in js,
then insert the chart to word document.

How can I do it?

**Comment by lindalu-MSFT** [comment]
@hengchengfei Hi, we have lots of documentation about how to work with Charts. This topic describes the basics about Charts using js: [Work with Charts using the Excel JavaScript API](https://dev.office.com/docs/add-ins/excel/excel-add-ins-charts)
However, if you're looking to do this in Word, you don't need js. You can create a chart from scratch directly in Word:

1. In your Word document, click Insert > Chart.
2. Select the type of chart you want, such as column or pie chart, and click OK. 
3. Enter your data into the spreadsheet that automatically opens with the chart.

You might try asking your question in [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) tag it office-js. This forum is specifically for errors/issues with the documentation set rather than the API itself. While there is certainly overlap, questions regarding the use of the library should be posted on Stack Overflow where you'll likely get a quicker response and benefit other developers facing the same challenges.
