### ISSUE TITLE
why there is no specific API for PowerPoint

### ISSUE THREAD

**Issue by nani2kt** [OfficeDev/office-js-docs#1331]

**Comment by kbrandl** [comment]
@nani2kt, you're correct in stating that there's currently no host-specific API available for PowerPoint. The Office.js API functionality that's currently available for PowerPoint is surfaced within the [Common APIs](https://dev.office.com/reference/add-ins/javascript-api-for-office).

Since this GitHub repository (**OfficeDev/office-js-docs**) is for reporting errors/issues with the API *documentation*, I'm closing this issue. However, I'd strongly recommend that you visit the [Office Dev UserVoice](https://officespdev.uservoice.com/) site and add your vote for [this Feature Request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/33200554-powerpoint-api), which another user submitted to request a host-specific API for PowerPoint. Feature Requests submitted via **UserVoice** are regularly reviewed by the product teams as they plan future releases of the Office.js APIs.
