### ISSUE TITLE
Office.context.mailbox.displayNewAppointmentForm() appointment form not opening with larger “body” text but not more than 32 KB

### ISSUE THREAD

**Issue by nehasoni3** [OfficeDev/office-js-docs#1409]
Hi,
I am developing a outlook add-in for mac OS using OfficeJs API.
As per the requirement, I am using **Office.context.mailbox.displayNewAppointmentForm()** method to open an Appointment window programatically, on the click of button.

  Office.context.mailbox.displayNewAppointmentForm(
  {
    location: '{Location}',
    subject: '{subject}',
    body: '{some large text}'
  });

If the **body** text is around 1600 characters or less, then the appointment window gets open with the pre-populated body, subject and location.
But if the body text exceeds that, then no appointment window is opened.
I know that there is a limit of 32 KB for the appointment form's body but my text is not more than 1.6 KB (I have confirmed it on character to KB converters).

[https://stackoverflow.com/questions/50135839/office-context-mailbox-displaynewappointmentform-appointment-form-not-opening](https://stackoverflow.com/questions/50135839/office-context-mailbox-displaynewappointmentform-appointment-form-not-opening)

**Comment by kbrandl** [comment]
This GitHub repository (**OfficeDev/office-js-docs**) is for reporting errors/issues with the API *documentation*.  Since you've already posted to Stack Overflow, a member of the product team will likely engage with you there about this issue. If you don't get the information you need via that Stack Overflow post, please feel free to log this as an issue in the **OfficeDev/office-js** repository, which members of the product team monitor for customer-reported API issues such as this.
