### ISSUE TITLE
Will database connectivity be implemented in office.js?

### ISSUE THREAD

**Issue by hobrob** [OfficeDev/office-js-docs#1516]
Will there ever be anything like the ADODB object implemented in office.js which will facilitate ODBC-like (presumably JDBC) connectivity? As a DBA, I've always found Excel VBA great for connecting to my DBMS (Teradata) and churning out custom charts for monitoring and the like at a button click. If I know this same connectivity will be implemented in the future I can at least start getting to know the Excel components that already exist in anticipation of building in database connections at a later date.

**Comment by kbrandl** [comment]
@hobrob thanks for your interest in Office.js. Since issues in this GitHub repository (**OfficeDev/office-js-docs**) are intended for providing feedback about the Office.js API Open Specifications, I'm closing this issue. 

But first, some feedback about your inquiry:

- Since an Office (web) Add-in is simply the web application that you create, plus an XML manifest that defines the add-in's settings and capabilities, you can build it to do whatever any web app is capable of doing -- including querying data from an external data source. Office.js provides APIs that enable your add-in to interact with the Office host (e.g., Excel, Word, etc.). If you want your add-in to query external data sources as you've described, it could certain do so -- but you'd be doing that via typical web dev techniques, not by using anything Office.js explicitly provides. 

I hope that helps. If you feel strongly that Office.js should provide something like you've described in your question, you might consider adding this feature request to the [Office Dev UserVoice](https://officespdev.uservoice.com/) site. Feature Requests submitted via **UserVoice** are regularly reviewed by the product teams as they plan future releases of the Office.js APIs.

**Comment by hobrob** [comment]
Thanks @kbrandl and apologies if I've posted this in the wrong area. On the one hand that makes a bit more sense now, on the other hand, possibly due to my being a bit behind the times when it comes to web dev, I'm a bit confused as to how this would hang together with just JavaScript and without some kind of server-side component that would do the DB connectivity bit. I think I just need to spend a bit of time getting to know the general concepts around add-ins first, think hard about what sort of end product I want to create, then go from there.
