### ISSUE TITLE
Possible new bug in getByNamespaceAsync method

### ISSUE THREAD

**Issue by hennievw** [OfficeDev/office-js-docs#250]
We noticed this morning that a piece of functionality in our application was no longer working. Upon investigation, the only logical explanation is that the Office.js on the CDN has been updated and some behaviour in code has changed.

We use : `Office.context.document.customXmlParts.getByNamespaceAsync` to obtain a custom XML file. 

In the past, when calling this method we would get an empty array as return if the file does not exist. Now, it seems it always returns a result item in the array  - even if it does not find it. The result item has all its properties set to “undefined”.

I’m not sure if this is an intended new behaviour or if it is maybe a bug, so I thought I’d report it.

**Comment by kbrandl** [comment]
@hennievw apologies for the lack of response. Are you still having trouble with this? The Office.js API and platform has evolved quite a bit since this issue was opened, so I suspect this may no longer be an issue. I'm going to close this issue, but if you're still having trouble, please feel free to log a new issue in the [OfficeDev/office-js](https://github.com/OfficeDev/office-js) repo, which is monitored by members of the product team.
