### ISSUE TITLE
Setting the "From" property on a message item

### ISSUE THREAD

**Issue by stefama** [OfficeDev/office-js-docs#251]
Could you confirm that setting the "From" property especially on email message items is disabled by design (From property is read only)? My need is to be able to programmatically set the From property to a office 365 group smtp address when a user needs to "send as" the group. Thanks.

**Comment by jasonjoh** [comment]
Can you link to the from property you're referring to?

**Comment by mlafleur** [comment]
That is correct, the [From property is read-only](http://dev.office.com/reference/add-ins/outlook/Office.context.mailbox.item#fromemailaddressdetails). Add-ins operate within a single mailbox (more accurately, a single email within a single mailbox). The From field will always return either the sender's address (in read mode) or the user's address (in compose mode). 

For this scenario I would recommend looking at Graph. Graph supports delegations (assuming the user has SendAs rights). See http://graph.microsoft.io/en-us/docs/api-reference/beta/resources/message for details.

**Comment by stefama** [comment]
Thanks for the pointer but I’m not sure I got your suggestion. I was looking into the Outlook JS API because I need to create an Outlook add-in that automates a few actions and, if possible, I wanted to avoid going the path of a VSTO add-in. Microsoft Graph looks to me like an API you would leverage when providing your own client GUI on top of O365 which I’m not. Am I missing something?

**Comment by mlafleur** [comment]
VSTO API's certainly provide a broader surface area and more granular control over the user experience. That said, you also give up the cross-platform benefits provided by Web Add-ins. If you need greater control and can live with being limited to Outlook for Windows, VSTO is still a valuable tool. 

Graph API is, as you point out, purely a REST API. It does not provide any interactive/user experience functionality itself. It does however cover a much broader surface area than either VSTO or Web Add-ins. Where Web Add-ins are scoped to a "mail item" and VSTO is scoped to Outlook, the Graph API is scoped to the user themselves. You can therefore interact with data well beyond a user's mailbox (OneDrive, SharePoint, etc). 

A common architectural design is to combine Web Add-ins and Graph API. Your Web Add-in provides the interactive elements (buttons, labels, forms, authentication, etc.) and your backend leverages Graph API to provide data otherwise out of the add-in's reach. 

To accomplish this the user will need to authenticate with Graph from within the add-in's user interface. This sounds a bit more complex than it is however. To the user they simply see a "Login with Microsoft" button the first time they launch the add-in. Your backend can then use the token to make calls into the Graph API. If you request the "offline_access" scope you also get a refresh_token which your backend can use to make calls to the API without the user being online. 

The [FindTime](https://findtime.microsoft.com/) add-in is a great example of this model. The UX is an add-in but most of the work going on is beyond an add-in's scope. By leveraging Graph API they are able to automate the scheduling process even though the email with the add-in activated has long since gone out to it's recipients.

**Comment by stefama** [comment]
Thank you for the extremely clear description and indeed the FindTime add-in is great at showcasing the type of results that together javascript add-ins and the Graph API allow. Too bad that the Outlook javascript API does not allow programmatically editing the From field while composing in Outlook, we were really caressing the idea of being able to have our add-in available also within OWA.

**Comment by mlafleur** [comment]
I completely understand and this is something that has been asked for in the past. It is a little more complex to implement than it seems at first. 

Under the covers there are two accounts involved, From and Sender. From is the account that owns the Mailbox while Sender is the account that is sending the message. This is where the operating scope issue comes into play, each of these accounts have distinct mailboxes. 

Since Graph is scoped to the Account level, it can do anything the account owner can do themselves. This includes sending mail "on behalf" of another user (assuming they have permission of course). 

Add-ins however are scoped to a Mailbox. So while your user may have permission to send emails on someone else's behalf, doing so requires switching mailboxes (from the Sender's to the From's). You add-in's execution environment suddenly changes, including the web browser's session context. In other words, switching mailboxes would be the last thing you add-in does before being terminated. 

Assuming the session context issue could be resolved, you still have an installation problem. You add-in may be installed on the Sender's mailbox but what happens if it hasn't been installed into the From account's mailbox? As soon as you switch mailboxes you would enter an environment your code cannot execute in (installing being equatable to "trust").
