### ISSUE TITLE
What kind of feedback are we supposed to be providing here?

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#266]
I'm confused about what type of issue/feedback to provide in this GitHub repo.

This site is referenced by page http://dev.office.com/reference/add-ins/openspec which indicates that feedback can be provided on the API itself.  However, this site is related to the documentation of the API's. Please clarify what type of issue/feedback should be provided here.

Thanks.

**Comment by sumurthy** [comment]
Hello @jbarr33 

The open-spec feedback we are seeking relates to API design, naming convention, missing or additional features needed for your scenario, priority, etc. Since the open design APIs are not available yet, this is not suitable for Stackoverflow forum. 

You can look at some of the recent Excel1.4 openspec issues/comments to get an idea. 

thank you
