### ISSUE TITLE
CoercionType.Ooxml not return the base64 image data in Task pane app word 2013

### ISSUE THREAD

**Issue by techvenky** [OfficeDev/office-js-docs#291]
I have used CoercionType.Ooxml to get base64 image format data, if i select only image using Ooxml CoercionType its works fine, but if i select some text and image i didn't get base64 image data.

Other Details:
Word version: 2013
App: Task pane App

**Comment by mlafleur** [comment]
Could you provide a snippet of the code you are using?

**Comment by techvenky** [comment]
Please find the below snippet to get the image and text from Add-in.

```
  Office.context.document.getSelectedDataAsync(
        Office.CoercionType.Ooxml,
        { valueFormat: Office.ValueFormat.Formatted, filterType: Office.FilterType.All },
        function (result) {
         
            var textArea = document.getElementById("dataOOXML");
            if (result.status == "succeeded") {

           
                currentOOXML = result.value;
             

                while (textArea.hasChildNodes()) {
                    textArea.removeChild(textArea.lastChild);
                }
                textArea.appendChild(document.createTextNode(currentOOXML));

                // Tell the user we succeeded
                report.innerText = "Got It --- Success!!";
            }
            else {
                // This runs if the getSelectedDataAsync method does not return a success flag
                currentOOXML = "";
                report.innerText = result.error.message;
            }
        });
}
```

**Comment by kbrandl** [comment]
@techvenky apologies for the lack of response on this. Are you still having trouble? The Office.js API and platform has evolved quite a bit since this issue was opened, so I suspect this may no longer be an issue. I'm going to close this issue, but if you're still having trouble, please feel free to either log a new issue in the [OfficeDev/office-js](https://github.com/OfficeDev/office-js) repo (if you think it's a bug with Office.js) or post a question to Stack Overflow and tag your question with the **office-js** tag (if your code isn't producing the results you're expecting and you'd like feedback on how to achieve your desired outcome).
