### ISSUE TITLE
User data and authentication with js api?

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-docs#31]
Can we get user data such as Live.com email via the JS api? Would love a snippet :) I would like to associate in app purchases to the logged in user, or prompt the user to login if they are anonymous. Would be convenient if I could use the Live.com user account.

**Comment by MIchaelMainer** [comment]
@giorgio79 Normally I'd point you at StackOverflow for a wonderful question like this one. Not today because the current state of connecting to Office 365 is [described in this blog post](http://blogs.msdn.com/b/richard_dizeregas_blog/archive/2015/08/10/connecting-to-office-365-from-an-office-add-in.aspx). But you mentioned live.com. Well, the same API you use to contact Office 365 is used to contact the Outlook.com service (I assume it is the same for Hotmail or Live). [Read more about it here](http://blogs.msdn.com/b/exchangedev/archive/2015/08/12/unified-outlook-apis-for-office-365-amp-outlook-com-are-here.aspx).

**Comment by giorgio79** [comment]
Thx Michael. Looks good but no candy :) I recommend a look on how Google Docs API can pass back the user email if the user is logged in :) The mentioned solutions are way too roundabout.
