### ISSUE TITLE
word add-in added successfully but it's not visible in shared folder.

### ISSUE THREAD

**Issue by MuthuRajSpiralUp** [OfficeDev/office-js-docs#339]

**Comment by mlafleur** [comment]
The most common reason this occurs is having multiple manifests with the same ID. Each add-in manifest must have a unique ID. 

Another common problem is the shared folder requiring authentication. Office will not prompt for credentials on the share folder. To resolve this you can open the folder in the file explorer and login. Office will be able to leverage those cached credentials to access the file share.

**Comment by jpmat296** [comment]
Microsoft Word 2013 (15.0.4893.1000)

For me the reason was bad &lt;Id&gt;. It looks like GUID value is now mandatory whereas some of your examples use text Id.

See manifest file [here](https://github.com/OfficeDev/office-js-docs/blob/eddb0c2e03be3f4bbfa6367a788247801dc0b192/docs/word/dictionary-task-pane-add-ins.md#creating-a-dictionary-add-ins-manifest-file). Extract:
`<Id>DemoDict</Id>

**Comment by mlafleur** [comment]
Excellent catch, thank you. It looks like that topic has an outdated example manifest (it is using the older 1.0 schema).
