### ISSUE TITLE
Office JS randomly throws "has not been fully loaded yet" on startup

### ISSUE THREAD

**Issue by roypeled** [OfficeDev/office-js-docs#348]
```javascript
Uncaught Office.js has not been fully loaded yet. Please try again later or make sure to add your initialization code on the Office.initialize function.
(anonymous function) @ Office.js:formatted:666 
d @ Office.js:formatted:250
setTimeout (async)d @ Office.js:formatted:246
setTimeout (async)d @ Office.js:formatted:246
setTimeout (async)d @ Office.js:formatted:246
setTimeout (async)d @ Office.js:formatted:246
```

This happens before any of my code tries to access Office's API. When the page loads, Office.js loads and then this error is thrown randomly. After that I the initialise function is never fired, and I can't access the API.

I'm loading the JS file from: https://appsforoffice.microsoft.com/lib/1/hosted/Office.js

**Comment by mlafleur** [comment]
Hello,
I would recommend posting questions like this on [Stackoverflow ](http://stackoverflow.com/questions/tagged/office-js)(tagged with `office-js`). This area is dedicated to issues with the documentation set rather than the library/API itself. 

That said, there could be a number of factors contributing to this error.  Typically we see this error when the initialize function was either not defined or a javascript error occurred prior to the function (i.e. malformed JS or an unhandled exception). In general the guidance is to always place the reference to Office.js in the header and to have Office.initialize be defined as early as possible (and if possible also in the page head).

**Comment by Lauragra** [comment]
I'm going to go ahead and close this issue for now. Feel free to reopen if we can further assist or clarify the documentation. Thanks.

**Comment by roypeled** [comment]
Thanks @mlafleur ! I got it! I assigned the init function after an async process, not on startup of my app. 

There should be a note in the documentation about it!

**Comment by jarleavloyp** [comment]
You help with this issue anyone?
