### ISSUE TITLE
Change the properties / Delete / Override custom style

### ISSUE THREAD

**Issue by ArtemZinenko** [OfficeDev/office-js-docs#368]
I can't do anything with the style after it was added using Body.InsertOoxml method.
Changing, deleting, overriding is not available after that.
Please tell me what to do with that.

**Comment by mlafleur** [comment]
Could you provide an example of the OOXML you are using and a bit more detail on "can't do anything"? Are you unable to interact with the content manually within Word or only programmatically?

**Comment by ArtemZinenko** [comment]
> Are you unable to interact with the content manually within Word or only programmatically? 
only programmatically

I attached 2 files, which contain the same "MyCustomStyle" style but style from first file has 24 font size and second has 48.
If we insert the ooxml consistently into the document, then eventually font size of "MyCustomStyle" will remain 24 but not 48. In fact, the style properties are not overwritten.

[First (Custom style with 24 font size.txt)](https://github.com/OfficeDev/office-js-docs/files/401698/Custom.style.with.24.font.size.txt)
[Second (Custom style with 48 font size.txt)](https://github.com/OfficeDev/office-js-docs/files/401697/Custom.style.with.48.font.size.txt)

**Comment by mlafleur** [comment]
Looking at the [documentation](http://dev.office.com/docs/add-ins/word/create-better-add-ins-for-word-with-office-open-xml#working-with-styles): 

> If a style is already in use in the destination document, your content will take on the resident definition for the style, regardless of what you include in styles.xml. If the style isn't yet in use in the destination document, your content will use the style definition you provide in the markup.

This implies that the behavior you are seeing is expected. If a given style is in use then it will continue to use the existing definition (even if you supplied an updated one). 

One possible workaround would be to generate a new style id rather than updating an existing style. Assuming that id is unique I would expect Word to simply add it the style to the document.

**Comment by Lauragra** [comment]
It sounds like this issue is resolved so closing for now. Feel free to reopen if you have additional questions. Thanks.
