### ISSUE TITLE
Change resolution of content add-in snapshot image

### ISSUE THREAD

**Issue by krebbl** [OfficeDev/office-js-docs#404]
The content-addin images get very blurry when exporting the pptx to PDF.
Is there a way to change the resolution of the saved image?

**Comment by keyur32** [comment]
Hi @krebbl, sorry for the delay. The snapshot depends on the zoom level. Here's some more info and background on this issue here: https://github.com/OfficeDev/office-js-docs/issues/689

To make it more clear, you could try to zoom the slide in, which will in effect cause the snapshot image to be a higher resolution. This is a limitation of the platform today, unfortunately.  We're looking at how we can improve this across platforms in the future.  I'm closing for now, but feel free to re-activate.
