### ISSUE TITLE
Excel API table resize

### ISSUE THREAD

**Issue by sumigoma** [OfficeDev/office-js-docs#42]
We have a use case involving many tables in the same sheet (that can be refreshed periodically with data of variable size). Currently, the Table object only supports deleting/adding rows or columns which will attempt to shift everything to the right or below. If the tables are staggered in the sheet, this can cause the refresh/paste operations to fail.

We would therefore like to modify the size of existing tables without shifting neighboring cells. Is it possible to expose the [ListObject.resize](https://msdn.microsoft.com/en-us/library/office/ff838369.aspx) method in the Excel API to resize Tables?

**Comment by sumigoma** [comment]
@sumurthy Any updates on this issue?

**Comment by sumurthy** [comment]
Hello @sumigoma We do have resize() API in the backlog for a while. It is not in the near-term because of some of the technical dependencies that needs to be met before this can be made available. 

We're working on how to communicate longer-term feature roadmap to the developers. In the meantime, do checkout the open-spec branches that informs of near-term new APIs that are under design/development.
