### ISSUE TITLE
Instructions do not pertain to Word 2016 for Mac

### ISSUE THREAD

**Issue by kdavidson007** [OfficeDev/office-js-docs#55]
The word-add-ins.md document states that the document applies to "Word 2016, Word for iPad, Word for Mac." Does "Word for Mac" refer to Word 2016 for Mac or to an older version? The instructions, starting with step 7, do not appear to pertain to the new Word 2016 for Mac. Is there an example of how to use an add-in with that version?

**Comment by MIchaelMainer** [comment]
This applies to Word 2016 for Mac. I'm going to update the content with the following information so that the add-in is visible:

1.	Create a folder called “wef” in Users/<username>/Library/Containers/com.microsoft.word/Data/Documents/
2.	Put the manifest in the wef folder (Users/<username>/Library/Containers/com.microsoft.word/Data/Documents/wef)
3.	Open Word 2016 on the Mac and click on insert->”my add-ins” drop down.

Use this in place of step #7.

**Comment by MIchaelMainer** [comment]
Added instructions to docs
