### ISSUE TITLE
Outlook: Detect if an email message was received or sent

### ISSUE THREAD

**Issue by mpk** [OfficeDev/office-js-docs#555]
Hi, I'm currently developing an Outlook add-in using Office JS API.

I would like to detect if the currently open email message was received from someone or sent by the user. I tried to implement this by checking if the email addresses in `Office.context.mailbox.item.from.emailAddress` and `Office.context.mailbox.userProfile.emailAddress` are equal or not.

However, this works only in Outlook web app and not in Outlook 2016, where the `item.from.emailAddress` is empty string for email messages sent by the user. Is this return value expected, or is it a bug in Outlook 2016?

Thank you in advance for your answer.

**Comment by jasonjoh** [comment]
Thanks for reporting this. Let me discuss with our dev team and get back to you.

**Comment by jasonjoh** [comment]
@mpk: A couple of things here.

1. It is expected that items in Sent Items will have a blank `item.from.emailAddress`. This is because those properties are set by the server as part of the mail submission process, not by Outlook.
2. However, there are other cases where it can be blank. I confirmed that this is a bug in Outlook. Basically if the message is missing the MAPI properties PR_SENDER_SMTP_ADDRESS and PR_SENT_REPRESENTING_SMTP_ADDRESS, then the from will be blank. We are working to fix this.
