### ISSUE TITLE
Missing word/numbering.xml in OOXML when retrieving bodyOOXML.value using JavaScript

### ISSUE THREAD

**Issue by yuanwei0525** [OfficeDev/office-js-docs#56]
When using JavaScript to get the OOXML body (bodyOOXML.value) as a string using the following code, the word/numbering.xml package is not included:

Word.run(function (context) {

```
// Create a proxy object for the document body.
var body = context.document.body;

// Queue a commmand to get the OOXML contents of the body.
var bodyOOXML = body.getOoxml();

// Synchronize the document state by executing the queued commands, 
// and return a promise to indicate task completion.
return context.sync().then(function () {
    console.log("Body OOXML contents: " + bodyOOXML.value);
});  
```

})
.catch(function (error) {
    console.log("Error: " + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log("Debug info: " + JSON.stringify(error.debugInfo));
    }
});

The word/styles.xml, word/fontTable.xml, etc. are included but without the numbering package we cannot recreate the number formats. Any help appreciated!

**Comment by lindalu-MSFT** [comment]
@JuaneloJuanelo Is this an active issue with no resolution? Is there a way to provide the "numbering package" in the sample? This open issue is almost 2 years old now. Please let me know how to proceed forward or simply close "won't fix."

**Comment by kbrandl** [comment]
@yuanwei0525 apologies for the lack of response on this. The Office.js API and platform has evolved quite a bit since this issue was opened, so I suspect this may no longer be an issue. I'm going to close this issue, but if you're still having trouble, please feel free to log a new issue in the [OfficeDev/office-js](https://github.com/OfficeDev/office-js) repo, which is monitored by members of the product team.
