### ISSUE TITLE
Office.js CDN outdated

### ISSUE THREAD

**Issue by klocke** [OfficeDev/office-js-docs#643]
According to your documentation, the recent Excel API version is 1.3.
To get the most recent version, you recommend using your CDN.
My following sample shows that it´s not the latest one.

Via Visual Studio or bower, I get even more outdated versions.
So, how am I supposed to get the latest version?

```
<!DOCTYPE html>
<html>

<head>
    <script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>
</head>

<body>
    <script>
        Office.initialize = function(reason) {
            var isExcelSupported = Office.context.requirements.isSetSupported('ExcelApi', 1.3);
            document.writeln('Is ExcelApi 1.3 supported? ' + isExcelSupported);

            Excel.run(function(ctx) {
                var sheet = ctx.workbook.worksheets.getActiveWorksheet();
                sheet.charts.getItemOrNull('test');
                document.writeln('Success!');
                return ctx.sync();
            }).catch(function(err) {
                document.writeln('Failure!');
            });
        }
    </script>
</body>

</html>
```

**Comment by sumurthy** [comment]
Hello @klocke, 

In order to get the latest API features, in addition to using the latest CDN (which is location for the latest JavaScript library) you'd also need to use the latest Excel client. Many of the new APIs require client updates as well. Only very few new APIs are JavaScript only additions, which could work on existing versions. 

In our docs, we have a column that indicates which Excel client versions are needed. Refer [here](https://github.com/OfficeDev/office-js-docs/blob/master/reference/requirement-sets/excel-api-requirement-sets.md) for details.

**Comment by jbosse** [comment]
Perhaps I am overlooking something but I think this is still an issue. For example I just started learning this today. The getting started yeoman build uses `https://appsforoffice.microsoft.com/lib/1.1/hosted/Office.debug.js`.

 I was trying to use  `worksheetCollectionObject.getItemOrNull` which the docs say is introduced in 1.3. but the CDN has no 1.3 and `https://appsforoffice.microsoft.com/lib/1/hosted/Office.js` has no implementation of `getItemOrNull` which makes me believe it is not serving 1.3. 

I am on macOS using Excel 15.28 which the docs state supports 1.3.
