### ISSUE TITLE
poor docs, lousy examples, wrong API

### ISSUE THREAD

**Issue by dtcode** [OfficeDev/office-js-docs#653]
on the one hand MS states to start with word 2013 and then you SHOW A 2016 EXAMPLE and for those of use who only have 2013 we endup having a mother F%%@$%@$#5EN example that doesn't work.... as usual. there's no where to go to get info or another example to try AGAIN.

**Comment by dcu-sharepoint** [comment]
The problem I'm having with the examples is that is SOOOO   INCOMPLETEEEEEE. 
 
Can YOU OR somebody please direct me to a forum or dev center office where I can ask questions.
 
The specific problems I'm having are: 
 
1) How to bind the controls in the word document to a SharePoint list. 
2) How to create a dynamic table control collections so it can be filled from list items.
 
These are critical as I have a customer waiting for a solution and I have not been able to find anything on the subject anywhere! We waste our time showing customer and hoping for the best, but this is ridiculous.
 
And I am sure I am NOT the ONLY ONE!
 
These tutorial create more confusion than the problem they are trying to solve. Look at the comment above, made on October 16, 2016, nearly 4 months ago and no response. What a way to run a business.
 
I demoed this example to one of my customers back in October and it is exactly the solution they need but I have not been able to give the solution to the customer because I can't find any information on how to bind the data from an Office 365 list to a table in a word document. I think the documentation, if written, was probably used as toilet paper BEFORE it was published so the information is in someone's rear end....
 
Sounds rude doesn't it, well the games you twits are playing with us are just as rude if not more so.
 
This is business and we need to treat it as a business NOT A GAME WITH A BACKLOG LIST.
 
I even called the 800 support but couldn’t get to anyone who can deal with this stuff.

**Comment by keyur32** [comment]
Hi @dtcode, sorry for your frustration. You're right, there was a topic that didn't call this out **clearly enough** and we've added a more prominent note.  The Word Javascript API requires Word 2016.  More information here: https://dev.office.com/add-in-availability.

To answer your question for Word 2013, you can build an add-in using the shared api or the "Office Javascript API". https://dev.office.com/reference/add-ins/javascript-api-for-office.    

Here are some other topics that may help you get started with Word 2013:
- https://dev.office.com/docs/add-ins/word/dictionary-task-pane-add-ins
- https://dev.office.com/docs/add-ins/develop/bind-to-regions-in-a-document-or-spreadsheet
- https://dev.office.com/docs/add-ins/develop/get-the-whole-document-from-an-add-in-for-powerpoint-or-word
- https://dev.office.com/docs/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet

If you run across any other instances that wasn't clear, let us know. I'm closing this issue for now, but feel free to re-activate or log another issue with anything related to the documentation.

**Comment by keyur32** [comment]
p.s. this was the topic that we changed up due to this: https://github.com/OfficeDev/office-js-docs/blob/master/docs/word/word-add-ins.md. thanks.

**Comment by dcu-sharepoint** [comment]
thank you Keyur for your great and informative answer.


however, I have read most of the docs you've mentioned, followed a few of the examples but none of them have an answer to the questions I have asked. in one instance I was directed to ask the question in the stackoverflow site only to get a "you have to comeup with a better title and do some research" answer by some idiot who did not provide an ounce of relevant information.


I still have a problem getting pertinent information on how to add/create controls on the word document of a a word add-in from the javaScript code and how to create a dynamic table and how to bind data to the actual controls all  from the javaScript code. if you go over the documents in your list, you wont' the information I have just listed in any of them unless you can point me to the document and prove me wrong in which case i'd be thanking profusely. it's amazing, you have created a beautiful platform but don't seem to want to share the customization knowledge with us developers, could it be that we might use it. the only ones that know are the platform creators and a few lucky partners, but the rest of us don't seem to be able to get answers by either paying, begging or anything else.


anywho: frustration is not the word i would use, but i'll keep clean and thank you for your answer.


Regards,


L. Carlos Rodriguez


________________________________

**Comment by dcu-sharepoint** [comment]
as has been the case with my problem.


CASE CLOSED AGAIN WITHOUT THE ANSWERS TO THE QUESTION. WHAT A WAY TO GO!


________________________________
