### ISSUE TITLE
OpenSpec-tableCollection-getItemOrNull

### ISSUE THREAD

**Issue by zbarresse** [OfficeDev/office-js-docs#669]
Would this work for the active workbook? Would you need to specify the sheet like you do in VBA, since Tables are child objects of the Worksheet object? Would you be able to specify the workbook? There is a notion of 'check if a table exists' that would be useful here as well.

**Comment by sumurthy** [comment]
Hello, 
Yes, this will work for current workbook where the add-in is running without specifying the worksheet. The specs for this API is [here](https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_1.4_OpenSpec/reference/excel/tablecollection.md#getitemornullobjectkey-number-or-string).

There is no plan for "Check if table exists" API. In order to check that, you'd have to either: check for .isNull? with `getItemOrNullObject()` API or handle not-found error with `getItem()`. 

Thanks for the comment.
