### ISSUE TITLE
OpenSpec-tableColumnCollection-add

### ISSUE THREAD

**Issue by zbarresse** [OfficeDev/office-js-docs#671]
Where do we specify the name of the column? Would the naming of the column be how Excel handles column naming by default? And what about position of the column to add? Also, what about adding more than one column?

**Comment by sumurthy** [comment]
Hello, 
The multi-column add is not supported yet. It is something we plan to do. 
The API takes in 3 parameters. index (0 index, use -1 for last position), values (2D-array), and optional column name. 
The way it is supposed to work is that if you provide column-name, it will be used for the first cell of the column. It looks like the API needs 1st cell anyway even with the column-name parameter. It may be a bug or just the way this API accepts the values parameter. I'll follow-up...

**Comment by sumurthy** [comment]
Sample [code](https://gist.github.com/sumurthy/a9a1ea95263e33a62960aa991f8ba170#file-app-js). It requires a table named Table1 to be in the spreadsheet with 5 rows. 

API spec is [here](https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_1.4_OpenSpec/reference/excel/tablecolumncollection.md#addindex-number-values-boolean-or-string-or-number-name-string)

**Comment by sumurthy** [comment]
Following up: 

The current column-add API has this behavior: 
1. Only adds 1 column at a time. 
2. You can add the column-name in two different ways: 
2.a: Use the values array with the [0,0] element of the 2-D array as the column heading. 
2.b: Use "name" parameter to specify the column-name. Due to backward compatibility, you'll still need to pass the [0,0] element in the values array. You can default that to `null` when you use the `name` parameter (3rd parameter).

We'll look to add add multiple columns in a single call.
