### ISSUE TITLE
Completing Named Item Support

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#684]
This may be a repeat of some other issues (#676 #678 #680) but I want to summarize.

To properly support Named Items requires
- ability to read and write the formula property of the name (VBA Name.RefersTo and variations
- ability to evaluate a Named Formula (VBA Application and Worksheet .Evaluate and VBA [Name] )

The other missing thing is the ability to create and read a Named Range using a range object (VBA Range.Name)

**Comment by sumurthy** [comment]
Excel evaluate can be tracked here: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/13702944-provide-api-to-evaluate-excel-formula

**Comment by kbrandl** [comment]
@FastExcel thanks for the feedback and apologies for the lack of engagement here in recent months. I'm closing this issue (since it's logged in UserVoice and covered by other issues as well). Please feel free to log feature requests like this in [UserVoice](https://officespdev.uservoice.com/) in the future. Thanks!
