### ISSUE TITLE
Microsoft office support?

### ISSUE THREAD

**Issue by dcu-sharepoint** [OfficeDev/office-js-docs#699]
**_is this crap being actively supported by MS?_**

there doesn't seem to be any answers or solutions coming from anybody on 99% of the issues being raised in this forum.

**Comment by mlafleur** [comment]
This form is for issues with the documentation itself (broken links, spelling errors, invalid grammar, broken examples, etc.). 

For support on the library itself, I'd suggest using Stack Overflow. There are several other sources out there but SO has a very active community that includes many of the engineers and PMs that work on Office.js directly. When posting there, because an tag your question appropriately or it can quickly get lost in the flood of questions. For Office.js related questions, I suggest using [office-js]: https://stackoverflow.com/questions/tagged/office-js. 

For feature requests, this User Voice is the proper play to surface them: https://officespdev.uservoice.com/.

**Comment by dcu-sharepoint** [comment]
Hello Mark,


it seems that SO is for users with Harvard or MIT degrees, otherwise all you seem to get from them is a cutdown if you make the slightest mistake and you don't get an answer for your question irregardless of how you phrase it.


I've asked a question about creating controls on a word document like it is being done in a github example but all I get is "goto SO" or this is not the place or whatever. even asking MS for paid support has not helped me in my instance so I had to tell my customer the technology is useless and not well documented.


so much for support.


sorry to be a PITA Mark but is frustrating dealing with technologies and their lack of support.


Carlos



________________________________

**Comment by mlafleur** [comment]
I'm sorry to hear you had a poor experience with SO. I've not experienced this myself and I certainly don't have a degree from Harvard or MIT. 

Tagging your post properly is about the more important guidance I can give. Failing to tag properly will result in your question surfacing to the wrong audience. Think of Tags like you would Forums where the tag you give a post is the forum you are posting that question to. Improper tagging is akin to asking Windows question in a Linux forum and unlikely to generate very helpful responses. Using `office-js` will ensure questions related to the Office JavaScript API surface for the audience you want.

**Comment by dcu-sharepoint** [comment]
Thanks for the advice Mark; been there done that as the saying goes....


but will go back and start the begging again, I need an answer to the issue and MS is NOT helping....


anywho: thanks again.


________________________________
