### ISSUE TITLE
Documentation about saving settings in Word on-line

### ISSUE THREAD

**Issue by lomagno** [OfficeDev/office-js-docs#768]
I'm using the settings API (https://dev.office.com/reference/add-ins/shared/document.settings) for saving settings data in a Word docx file. I noticed that settings data are saved in the file (I checked that by inspecting the saved xml in the Word document), but they can only be retrieved in Office 365 and not in Office on-line.
I tested this by developing an Word Office add-in. I run this add-in in Office on-line and in Office 365. I created settings data in Word on-line and then downloaded the created docx. This docx has settings saved inside, and I'm sure of this because I inspected the XML. This settings data can then be read in Office 365, but not in Office on-line, by using the same add-in that created the settings data.
Is it a missing in the documentation or it is natural that I can read settings only from Office 365?

**Comment by sumurthy** [comment]
Can you please explain what you mean by Office 365 and Office online? Office 365 gives you suite of apps and services, one of which is Office apps (including browser edition). Office Online "Server" is a separate product that only gives you browser apps for viewing/editing Office documents. That version is usually few months behind the latest version and what I suspect is that you are using two different versions of OffficeJs to test.

**Comment by lomagno** [comment]
Sorry, the difference I noticed is between Office online and the traditional Office (desktop version for Windows). The OfficeJs I used is the latest available at the time of posting this issue to GitHub (February 23). In fact, I used the following tag in my html:

`<script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" type="text/javascript"></script>`

This ensures the latest version.
Thus, for clarity reasons, I prefer to reformulate the issue: "I tested this by developing an Word Office add-in. I run this add-in in Office on-line and in Office for Windows. I created settings data in Word on-line and then downloaded the created docx. This docx has settings saved inside, and I'm sure of this because I inspected the XML. This settings data can then be read in Office for Windows, but not in Office on-line, by using the same add-in that created the settings data.
Is it a missing in the documentation or it is natural that I can read settings only from Office 365?"
This issue is not more of interest for me, because I decided to not use the "settings" functionality. Thus, I do not need anymore your reply to this issue. Nethertheless I suggest you to check if there is a bug or the problem is that the Office OnLine is few months behind the latest version.

**Comment by mlafleur** [comment]
I suspect you're side-loading your add-in. When you side-load an add-in it generates a unique ID. This ensures you don't run into conflicts between your production and development versions of your add-in (since they likely would use the same ID in the manifest). 

Settings are stored within the document itself but linked to the add-in ID. This ensures your settings don't step on or get stepped on when a user has multiple add-ins installed in a document.  Since you're desktop and online versions have two different ID's, this is why you're settings don't seem to carry over. 

If you want to test settings, I recommend setting up a Developer Tenant and deploy your manifest in there. That will allow you to maintain the same ID across Windows, Mac and Online editions.

**Comment by lomagno** [comment]
I think your explanation is probably correct. Nethertheless I am not more interested in this functionality and I should admit that I will not investigate this issue in the near future. Thank you very much for you attention.
