### ISSUE TITLE
Why is itemId unavailable for existing appointments in compose-mode?

### ISSUE THREAD

**Issue by kasperdaff** [OfficeDev/office-js-docs#798]
What's the reason for not being able to obtain an existing appointment's itemId in compose-mode?

Unlike emails, appointments are frequently being edited. So an appointment will likely be opened in compose-mode multiple times in its lifecycle, e.g. when being rescheduled.

I know I can obtain the itemId by saving the appointment, but that's very invasive as it saves or updates the appointment in the user's calendar without the user's consent. Moreover, if it's a new appointment (which it no longer is after saving it), it will leave behind an empty "ghost-like"  appointment in the user's calendar, e.g. when the user regrets making the appointment and closes it. And as far I know, it's also not possible to discern whether an appointment opened in compose-mode is new or existing?

From an API point-of-view, accessing itemId of an appointment should behave as follows, regardless of add-in mode:

1) Return undefined (or null) when the appointment _hasn't_ been persisted in Exchange (i.e. a new, unsaved appointment)
2) Return the id when appointment _has_ been persisted in Exchange (i.e. an existing appointment)

I really struggle to see the justification for the current behavior, so can you please shed some light on it?

**Comment by jasonjoh** [comment]
Hi @kasperdaff, thanks for reaching out. Essentially the "compose" mode scenario makes no attempt to retrieve an ID since in the majority of cases there isn't one. I know it's a little odd in the appointment scenario since an appointment is always in "compose" for the organizer, but that's where we are today.

I recommend leaving this as feedback to the dev team at https://officespdev.uservoice.com/.
