### ISSUE TITLE
Office.js on Outlook for Mac: Internal Error on saveAsync method

### ISSUE THREAD

**Issue by alekkowalczyk** [OfficeDev/office-js-docs#805]
Remark: I posted this question on StackOverflow as suggested, but didn't get any answer, whereas on the MSDN forums I got an answer to ask over here. - Getting help with the new office.js is really hard sometimes.

So office.js add-in support is finally out for Outlook for Mac since version 15.32.
I'm actually using the latest non-insider version 15.33, and have one issue that doesn't take place on OWA or Outlook Desktop for Windows.

When I make following call in the add-in to get the event id:

    const itemCompose = Office.cast.item.toItemCompose(Office.context.mailbox.item);
    itemCompose.saveAsync((result) => console.log(result));

on OWA and Outlook Windows result.value has the event id, however on Outlook for Mac that is the result:

    {
     error: Error {name: "Internal Error", message: "An internal error has occurred.", code: 5001}
     status: "failed"
     value: null
    }

is it a bug in the freshly released office.js support for Outlook for Mac, or I'm doing something wrong?

**important note**: it happens only if the event has some attendees, that is, if the event is an meeting. On an appointment, so an event without attendees, it works as expected.

**Comment by jasonjoh** [comment]
@alekkowalczyk sorry for the confusion. I found your SO post. It didn't hit my watch filters because it wasn't tagged with `outlook-web-addins`. I know it's a little confusing, but the `outlook-addins` tag is related to the old COM add-in model. 

In any event, I posted an answer to SO. Mac Outlook doesn't support saving meetings in compose mode, which is something I just found out from the Mac team today :). I'll update the docs for `saveAsync` so this is clear.
