### ISSUE TITLE
Invalid manifest file

### ISSUE THREAD

**Issue by outsideMyBox** [OfficeDev/office-js-docs#877]
The manifest file in https://dev.office.com/docs/add-ins/word/word-add-ins#give-us-your-feedback
doesn't pass the validation tool validate-office-addin. I also get an error if I try to upload it with the Office 365 admin center.

**Comment by Rick-Kirkham** [comment]
@outsideMyBox 
You are correct that the simple manifest in this article is missing two elements that are required for selling an add-in in the Office store. Since the tool you used taps into the same XSD as the store, the manifest fails validation. However, this does not prevent it from working as it should in the context of this article. Adding the two missing elements would significantly complicate this article. (Among other things, the article would have to instruct the user to create/obtain an icon file of a certain size.) For that reason, I think it's best to leave the manifest in this article as it is. Readers who are finished with this article and ready to go on to more advanced work, should not use the manifest in this article as a starting point. The next step should be to start using the project generation tools (VS and/or yeoman) which will generate manifest files. See [create-and-debug-office-add-ins-in-visual-studio](https://dev.office.com/docs/add-ins/get-started/create-and-debug-office-add-ins-in-visual-studio)  or [create-an-office-add-in-using-any-editor](https://dev.office.com/docs/add-ins/get-started/create-an-office-add-in-using-any-editor).
